# Generated by Django 4.2.5 on 2023-11-13 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(max_length=300, upload_to='images', verbose_name='Kart resmi ekleyin')),
                ('brand', models.CharField(max_length=50, verbose_name='Marka Ekleyin')),
                ('category', models.CharField(choices=[('Telefon', 'Telefon'), ('Bilgisayar', 'Bilgisayar'), ('Tablet', 'Tablet')], max_length=50, verbose_name='Kategori ekleyin Ekleyin')),
                ('title', models.TextField(verbose_name='Kart başlığı ekleyin')),
            ],
        ),
    ]
