# Generated by Django 4.2.5 on 2023-11-13 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cards',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Ürün başlığı ekleyin'),
        ),
    ]
