# Generated by Django 4.2.5 on 2023-11-16 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_cards_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='cards',
            name='slug',
            field=models.SlugField(null=True, verbose_name='Slug'),
        ),
    ]
