# Generated by Django 4.2.5 on 2023-11-16 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_cards_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cards',
            name='slug',
            field=models.SlugField(blank=True, null=True, verbose_name='Slug'),
        ),
    ]
