# Generated by Django 4.2.5 on 2023-11-16 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_yorum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yorum',
            name='user',
        ),
    ]
