# Generated by Django 4.2.5 on 2023-11-16 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_yorum_card_alter_yorum_raiting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yorum',
            name='raiting',
        ),
    ]
