# Generated by Django 4.2.5 on 2023-11-21 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_remove_yorum_raiting'),
    ]

    operations = [
        migrations.CreateModel(
            name='register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Kullanıcı adı')),
                ('password', models.CharField(max_length=50, verbose_name='Parola')),
                ('email', models.EmailField(max_length=254, verbose_name='Email adresi')),
            ],
        ),
    ]
