# Generated by Django 4.2.5 on 2023-11-27 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_favori'),
    ]

    operations = [
        migrations.AddField(
            model_name='yorum',
            name='user',
            field=models.CharField(max_length=50, null=True, verbose_name='Kullanıcı'),
        ),
    ]
