# Generated by Django 4.2.5 on 2023-11-29 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_yorum_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cards',
            name='category',
            field=models.CharField(choices=[('Film', 'Film'), ('Dizi', 'Dizi'), ('Belgesel', 'Belgesel')], max_length=50, verbose_name='Kategori ekleyin Ekleyin'),
        ),
    ]
